# Generated by Django 4.2.9 on 2025-02-03 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_phone_verified_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name="Sarlavha (O'zbek)")),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (Русский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_uz', models.TextField(verbose_name="Tavsif (O'zbek)")),
                ('description_ru', models.TextField(verbose_name='Описание (Русский)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('image', models.ImageField(upload_to='banner_images/', verbose_name='Rasm')),
                ('url', models.URLField(blank=True, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbek)")),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
            ],
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=100, verbose_name='Название (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=1, max_length=100, verbose_name="Nomi (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(default=1, max_length=100, verbose_name='Название (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name_uz',
            field=models.CharField(default=1, max_length=100, verbose_name="Nomi (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cashback_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cashback_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yetkazib berish sanasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (Русский)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name="Tavsif (O'zbek)"),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Rasm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='installment_period',
            field=models.IntegerField(default=12, verbose_name="To'lov muddati"),
        ),
        migrations.AddField(
            model_name='product',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name="Oylik to'lov"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Название (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name="Nomi (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10, verbose_name='Narx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_en',
            field=models.CharField(default=1, max_length=50, verbose_name='Color (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_ru',
            field=models.CharField(default=1, max_length=50, verbose_name='Цвет (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_uz',
            field=models.CharField(default=1, max_length=50, verbose_name="Rang (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Mavjud'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_en',
            field=models.CharField(default=1, max_length=50, verbose_name='Size (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_ru',
            field=models.CharField(default=1, max_length=50, verbose_name='Размер (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_uz',
            field=models.CharField(default=1, max_length=50, verbose_name="O'lcham (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cashback balansi'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='content_en',
            field=models.TextField(default=1, verbose_name='Content (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useragreement',
            name='content_ru',
            field=models.TextField(default=1, verbose_name='Содержание (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useragreement',
            name='content_uz',
            field=models.TextField(default=1, verbose_name="Mazmun (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useragreement',
            name='title_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useragreement',
            name='title_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useragreement',
            name='title_uz',
            field=models.CharField(default=1, max_length=200, verbose_name="Sarlavha (O'zbek)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.region'),
            preserve_default=False,
        ),
    ]
