# Generated by Django 4.2.9 on 2025-02-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner_region_delete_promotion_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
    ]
