# Generated by Django 4.2.9 on 2025-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_banner_end_date_remove_banner_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Rasm'),
        ),
    ]
