# Generated by Django 4.2.9 on 2025-02-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
