# Generated by Django 4.2.9 on 2025-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installment_period',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name="To'lov muddati"),
        ),
    ]
