# Generated by Django 4.2.9 on 2025-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_image_alter_product_installment_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='installment_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='monthly_payment_12',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10, verbose_name="12 oylik to'lov"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='monthly_payment_24',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10, verbose_name="24 oylik to'lov"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='monthly_payment_3',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10, verbose_name="3 oylik to'lov"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='monthly_payment_6',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10, verbose_name="6 oylik to'lov"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
