# Generated by Django 4.2.9 on 2025-02-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Uzunlik')),
                ('address_uz', models.TextField(verbose_name="Manzil (O'zbek)")),
                ('address_ru', models.TextField(verbose_name='Адрес (Русский)')),
                ('address_en', models.TextField(verbose_name='Address (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy manzil')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name="Sarlavha (O'zbek)")),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (Русский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('description_uz', models.CharField(max_length=255, verbose_name="Tavsif (O'zbek)")),
                ('description_ru', models.CharField(max_length=255, verbose_name='Описание (Русский)')),
                ('description_en', models.CharField(max_length=255, verbose_name='Description (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Qo'llab-quvvatlash",
                'verbose_name_plural': "Qo'llab-quvvatlash xizmatlari",
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Rasm'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name="Nomi (O'zbek)")),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('address_uz', models.TextField(verbose_name="Manzil (O'zbek)")),
                ('address_ru', models.TextField(verbose_name='Адрес (Русский)')),
                ('address_en', models.TextField(verbose_name='Address (English)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('working_hours_uz', models.CharField(max_length=100, verbose_name="Ish vaqti (O'zbek)")),
                ('working_hours_ru', models.CharField(max_length=100, verbose_name='Рабочее время (Русский)')),
                ('working_hours_en', models.CharField(max_length=100, verbose_name='Working Hours (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='main.location')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order'],
            },
        ),
    ]
