# Generated by Django 4.2.9 on 2025-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_cashback_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tasdiqlash urinishi vaqti'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_attempts',
            field=models.IntegerField(default=0, verbose_name='Tasdiqlash kodi yuborish urinishlari'),
        ),
    ]
