# Generated by Django 4.2.9 on 2025-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_last_verification_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.IntegerField(choices=[('0', "O'zi olib ketish"), ('1', 'Yetkazib berish')], default=1, verbose_name='Yetkazib berish usuli'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[('0', 'Naqd pul'), ('1', 'Click'), ('2', 'Payme'), ('3', "Bo'lib to'lash")], default=0, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('0', 'Kutilmoqda'), ('1', 'Jarayonda'), ('2', "Jo'natildi"), ('3', 'Yetkazib berildi'), ('4', 'Bekor qilindi')], default='0', verbose_name='Holat'),
        ),
    ]
