# Generated by Django 4.2.9 on 2025-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', "O'zi olib ketish"), ('delivery', 'Yetkazib berish')], max_length=20, verbose_name='Yetkazib berish usuli'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('click', 'Click'), ('payme', 'Payme'), ('installments_payment', "Bo'lib to'lash")], max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('shipped', "Jo'natildi"), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
