# Generated by Django 4.2.9 on 2025-02-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_socialmedia_remove_support_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
