# Generated by Django 4.2.9 on 2025-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_banner_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.IntegerField(default=0),
        ),
    ]
