# Generated by Django 4.2.9 on 2025-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_banner_branch_category_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='support',
            name='branch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='branch',
            field=models.IntegerField(default=0),
        ),
    ]
