# Generated by Django 4.2.9 on 2025-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', "O'zi olib ketish"), ('delivery', 'Yetkazib berish')], max_length=20, null=True, verbose_name='Yetkazib berish usuli'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd pul'), ('click', 'Click'), ('payme', 'Payme'), ('installments_payment', "Bo'lib to'lash")], max_length=20, null=True, verbose_name="To'lov usuli"),
        ),
    ]
