# Generated by Django 4.2.9 on 2025-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amocrm_lead_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
