# Generated by Django 4.2.9 on 2025-03-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_amocrm_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amocrm_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
