# Generated by Django 4.2.9 on 2025-03-18 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_order_amocrm_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_finished', models.BooleanField(default=False, verbose_name="To'lov yakunlangan")),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payme_order', to='main.order', verbose_name='Payme Buyurtma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
