# Generated by Django 4.2.9 on 2025-03-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_paymeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Rasm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color (English)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет (Русский)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Rang (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size (English)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер (Русский)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="O'lcham (O'zbek)"),
        ),
    ]
