# Generated by Django 4.2.9 on 2025-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_product_image_alter_productvariant_color_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCRMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='part',
            field=models.IntegerField(choices=[(0, 'Stroy baza'), (1, 'Giaz mebel'), (2, 'Gold Klinker')], default=0),
        ),
    ]
