# Generated by Django 4.2.9 on 2025-03-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_amocrmtoken_order_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_payment', "To'lov jarayonida"), ('processing', 'Jarayonda'), ('shipped', "Jo'natildi"), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.DeleteModel(
            name='PaymeOrder',
        ),
    ]
