# Generated by Django 5.1.2 on 2025-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ikpu',
            field=models.IntegerField(default=1, verbose_name='ikpu raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(default='dona', max_length=100, verbose_name="o'lchov birligi nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='units_id',
            field=models.IntegerField(default=1377058, verbose_name="o'lchov birligi raqami"),
        ),
    ]
