# Generated by Django 5.1.2 on 2025-04-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_product_ikpu_product_units_product_units_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ikpu',
            field=models.BigIntegerField(verbose_name='ikpu raqami'),
        ),
    ]
