# Generated by Django 5.1.2 on 2025-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_product_ikpu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='units',
            new_name='units_en',
        ),
        migrations.AddField(
            model_name='product',
            name='units_ru',
            field=models.CharField(default='dona', max_length=100, verbose_name="o'lchov birligi nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='units_uz',
            field=models.CharField(default='dona', max_length=100, verbose_name="o'lchov birligi nomi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='ikpu',
            field=models.CharField(max_length=100, verbose_name='ikpu raqami'),
        ),
    ]
