# Generated by Django 5.1.2 on 2025-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_units_product_units_en_product_units_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_en',
            field=models.CharField(default='dona', max_length=100, verbose_name="o'lchov birligi nomi (Русский)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_ru',
            field=models.CharField(default='dona', max_length=100, verbose_name="o'lchov birligi nomi (English)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_uz',
            field=models.CharField(default='dona', max_length=100, verbose_name="o'lchov birligi nomi (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_en',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Size (English)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_ru',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер (Русский)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_uz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="O'lcham (O'zbek)"),
        ),
    ]
