# Generated by Django 5.1.2 on 2025-04-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_product_units_en_alter_product_units_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Size (English)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер (Русский)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_uz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="O'lcham (O'zbek)"),
        ),
    ]
